#!/bin/sh

function __grvmEval {
	eval "$@"
}

function __grvmUpgrade {
	availableVersion=$(curl -s https://api.github.com/repos/Bugagazavr/grvm/releases/latest | grep 'tag_name' | cut -d\" -f4 | tail -c +2)
	currentVersion=$(__grvmFn --version | awk '{print $3}')

	if [[ "$availableVersion" == "$currentVersion" ]]; then
		echo "You have latest GRVM $currentVersion"
	else
		curl -s https://raw.githubusercontent.com/Bugagazavr/grvm/master/install.sh | bash --
	fi
}

function __grvmFn {
	case $1 in
		"init")
			arg=`$HOME/.grvm/bin/grvm -s env`
			__grvmEval $arg
			;;
		"set"|"use")
			arg=`$HOME/.grvm/bin/grvm -s set $2 $3 $4 $5`
			__grvmEval $arg
			;;
		"upgrade")
			__grvmUpgrade
			;;
		*)
			$HOME/.grvm/bin/grvm "$@"
			;;
	esac
}

alias grvm=__grvmFn

__grvmFn init
